version: '3.8'

networks:
  cyclenet:
    driver: bridge
    name: cyclenet
    
services:
  cycle-store:
    container_name: cycle-store
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH:neo4j/neo4j}
    image: neo4j:5.15.0-bullseye
    networks:
      - cyclenet
    ports:
      - 7474:7474
      - 7373:7373
      - 7687:7687
    restart: always