version: '3.8'

networks:
  cyclenet:
    driver: bridge
    name: cyclenet
    
services:
  cycle-store:
    container_name: cycle-store
    image: neo4j:5.15.0-bullseye
    ports:
      - 7474:7474
      - 7373:7373
      - 7687:7687
    restart: always
    networks:
      - cyclenet